### ISSUE TITLE
%player_name%  - doesn't work

### ISSUE THREAD

**Issue by ipaulocesar** [LOOHP/LotterySix#10]
> The %player_name% function is not working, I have tried several ways to try to revert it and nothing works, it does not show the player's name.
> 
> I'm using all updated dependencies.
> I'm not receiving any error notices, everything is running perfectly well.
> I know I could simply delete the function from this line and the others, but that would lose the character of your work.
     BettingAccount:
      _- '&e%player_name%''s Betting Account'_
      - '&7View details of your betting account'

![Captura de tela 2024-08-09 165621](https://github.com/user-attachments/assets/1fddb426-a380-40b9-a444-6ede5542c950)
![Captura de tela 2024-08-09 171532](https://github.com/user-attachments/assets/6082df92-fd2e-4cc0-817a-4980b2872533)
![Captura de tela 2024-08-09 165632](https://github.com/user-attachments/assets/25b11af0-ed87-4e74-aade-3c29db8741ce)
![image](https://github.com/user-attachments/assets/df5b0771-97cb-44de-b27d-84d2749e9b2b)

**Comment by LOOHP** [comment]
Did you install the PAPI Player expansion?

**Comment by ipaulocesar** [comment]
### Thank you, now everything is working fine.

/papi ecloud download Player

/papi reload

[https://api.extendedclip.com/expansions/player/](url)

![image](https://github.com/user-attachments/assets/1ca10915-66b8-4a8c-82e1-248d845acbe9)

**Comment by LOOHP** [comment]
Awesome, and thanks for putting down the steps you took to solve it for future readers.
