### ISSUE TITLE
folia unsupported

### ISSUE THREAD

**Issue by opierice** [LOOHP/LotterySix#5]
when I installed it on my folia server, it prompted me to download the PlaceholderAPI, but the PlaceholderAPI plugin does not currently support Folia. how can I use your plugin on my folia server(1.20.4-folia)

**Comment by LOOHP** [comment]
It is a [planned feature](https://github.com/PlaceholderAPI/PlaceholderAPI/pull/980) in PlaceholderAPI.
If you don't want to wait, you can build the plugin from that PR.

**Comment by opierice** [comment]
okay thx
