### ISSUE TITLE
The deposit GUI cannot be opened

### ISSUE THREAD

**Issue by CaesarGalahad** [LOOHP/LotterySix#9]
When the deposit button is clicked,
the GUI closes and nothing is displayed,
and the console reports an error

Server INFO
server version purpur-2265 MC-1.21
LotterySix version 1.10.14.0

LOG
[BUG-Log.txt](https://github.com/user-attachments/files/16267763/BUG-Log.txt)

**Comment by LOOHP** [comment]
Should be fixed in 1.10.15. Thanks for reporting!
